- hosts: master
  become: yes
  tasks:
   - name: remove swap
     shell: "swapoff -a"
 
   - name: Start the cluster
     shell: kubeadm init --pod-network-cidr=10.244.0.0/16 >> cluster.txt
     args:
       chdir: $HOME
       creates: cluster.txt
 
   - name: create .kube directory
     become: yes
     become_user: nitesh
     file:
      path: $HOME/.kube
      state: directory
      mode: 0755
 
   - name: copy admin.conf to user's kube config
     copy:
      src: /etc/kubernetes/admin.conf
      dest: /home/nitesh/.kube/config
      remote_src: yes
      owner: nitesh
 
   - name: install Pod network
     become: yes
     become_user: nitesh
     shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml >> pod_network_setup.txt
     args:
      chdir: $HOME
      creates: pod_network_setup.txt
