version: '3'
services:
  first:
    build:
      context: ./first
      dockerfile: Dockerfile
      args: 
        - CENTOS_VERSION=${CENTOS_VERSION}
    image: nitesh99sharma/hello_world:1.0
    
    networks:
       - mynet
    ports:
      - 80:5000
    volumes:
      - myvol:/data
  second:
    build:
      context: ./second
      dockerfile: Dockerfile
      args:
        - CENTOS_VERSION=${CENTOS_VERSION}
    image: nitesh99sharma/hello_world:2.0
    volumes:
       - myvol:/mydata
    networks:
       - mynet
    ports:
      - 5000:5000
networks:
  mynet:

volumes:
  myvol:
